code --install-extension aaron-bond.better-comments
code --install-extension abusaidm.html-snippets
code --install-extension alefragnani.project-manager
code --install-extension bengreenier.vscode-node-readme
code --install-extension burkeholland.simple-react-snippets
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension donjayamanne.githistory
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension EditorConfig.EditorConfig
code --install-extension eg2.vscode-npm-script
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension GitLab.gitlab-workflow
code --install-extension christian-kohler.npm-intellisense
code --install-extension johnpapa.winteriscoming
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension kamikillerto.vscode-colorize
code --install-extension leizongmin.node-module-intellisense
code --install-extension mgmcdermott.vscode-language-babel
code --install-extension mohsen1.prettify-json
code --install-extension mrmlnc.vscode-scss
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension oderwat.indent-rainbow
code --install-extension PKief.material-icon-theme
code --install-extension pomber.git-file-history
code --install-extension rafamel.subtle-brackets
code --install-extension ritwickdey.LiveServer
code --install-extension ruiquelhas.vscode-lowercase
code --install-extension ruiquelhas.vscode-uppercase
code --install-extension SirTori.indenticator
code --install-extension tomoki1207.pdf
code --install-extension Tyriar.shell-launcher
code --install-extension vincaslt.highlight-matching-tag
code --install-extension wayou.vscode-todo-highlight
code --install-extension webstp.extension-manager
code --install-extension xabikos.JavaScriptSnippets
code --install-extension xabikos.ReactSnippets
code --install-extension yzhang.markdown-all-in-one
